version: "3.3"

services:
  univ_auth:
    image: univ_auth:latest
    container_name: univ_auth
    environment:
      - NODE_ENV=docker
      - ADMIN_ACCOUNT=admin@auth.fr
      - ADMIN_PWD=admin
    ports:
      - "3000:3000"

  univ_mongo:
    image: mongo:3.4
    container_name: univ_mongo
    ports:
      - "27017:27017"